### ISSUE TITLE
context 를 2개로 나눠서 처리하는 이유는 무엇인가요?

### ISSUE THREAD

**Issue by visualkhh** [sangheon-kim/react-media-all#30]
context 를 2개로 나눠서 처리하는 이유는 무엇인가요?
- stateCtx
- dispatchCtx

하나의 context에 
reducer넣어서 처리하면 두번감싸지 않고 한번 감싸처리되니 깔끔해질것같은데..
두개쓰셔서 한 이유가 궁금합니다.😀

**Comment by sangheon-kim** [comment]
저때는 제가 너무 부족할때여서 저도 ㅠㅠ 지금 보니 왜 저렇게 짰나 싶네요 조만간 각잡고 개선한번 할게요 ㅎㅎ
